announcement:
  label: Announcement
  permalink: /announcement

paracore:
  label: Paracore
  permalink: /paracore

revit:
  label: Revit
  permalink: /revit

automation:
  label: Automation
  permalink: /automation

story:
  label: Story
  permalink: /story

developers:
  label: Developers
  permalink: /developers

architecture:
  label: Architecture
  permalink: /architecture

ai:
  label: AI
  permalink: /ai

facebook:
  label: Facebook
  permalink: /facebook
  description: Facebook tag description

hello:
  label: Hello
  permalink: /hello
  description: Hello tag description

docusaurus:
  label: Docusaurus
  permalink: /docusaurus
  description: Docusaurus tag description

hola:
  label: Hola
  permalink: /hola
  description: Hola tag description